<?php
/**
 * Language helpers for front-end copy, admin copy and answer rules.
 *
 * @package JeroensChatbox
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class JCB_Language {

	/**
	 * Supported plugin languages.
	 */
	public static function languages(): array {
		return array(
			'en' => array(
				'name'    => 'English',
				'native'  => 'English',
				'strings' => array(
					'welcome_message' => 'Hi. How can I help you?',
					'placeholder'     => 'Ask a question...',
					'launcher_label'  => 'Chat',
					'instructions'     => 'Answer questions using the selected website knowledge base. Be clear, helpful and honest. If the answer is not in the knowledge base, say that you do not know based on the available site content.',
					'send'             => 'Send',
					'close'            => 'Close',
					'typing'           => 'Typing...',
					'sources'          => 'Sources',
					'source'           => 'Source',
					'helpful'          => 'Helpful',
					'not_helpful'      => 'Not helpful',
					'feedback_thanks'  => 'Thanks for your feedback.',
					'error_answer'     => 'The chatbox could not answer right now.',
					'no_answer'        => 'No answer returned.',
				),
				'admin'   => self::admin_en(),
			),
			'nl' => array(
				'name'    => 'Dutch',
				'native'  => 'Nederlands',
				'strings' => array(
					'welcome_message' => 'Hoi. Waar kan ik je mee helpen?',
					'placeholder'     => 'Stel je vraag...',
					'launcher_label'  => 'Chat',
					'instructions'     => 'Beantwoord vragen met de geselecteerde kennisbank van de website. Wees duidelijk, behulpzaam en eerlijk. Als het antwoord niet in de kennisbank staat, zeg dan dat je het niet weet op basis van de beschikbare site inhoud.',
					'send'             => 'Verstuur',
					'close'            => 'Sluiten',
					'typing'           => 'Aan het typen...',
					'sources'          => 'Bronnen',
					'source'           => 'Bron',
					'helpful'          => 'Nuttig',
					'not_helpful'      => 'Niet nuttig',
					'feedback_thanks'  => 'Bedankt voor je feedback.',
					'error_answer'     => 'De chatbox kan nu geen antwoord geven.',
					'no_answer'        => 'Geen antwoord ontvangen.',
				),
				'admin'   => self::admin_nl(),
			),
			'de' => array(
				'name'    => 'German',
				'native'  => 'Deutsch',
				'strings' => array(
					'welcome_message' => 'Hallo. Wie kann ich dir helfen?',
					'placeholder'     => 'Stelle eine Frage...',
					'launcher_label'  => 'Chat',
					'instructions'     => 'Beantworte Fragen mit der ausgewählten Wissensdatenbank der Website. Sei klar, hilfreich und ehrlich. Wenn die Antwort nicht in der Wissensdatenbank steht, sage, dass du es anhand der verfügbaren Website Inhalte nicht weißt.',
					'send'             => 'Senden',
					'close'            => 'Schließen',
					'typing'           => 'Tippt...',
					'sources'          => 'Quellen',
					'source'           => 'Quelle',
					'helpful'          => 'Hilfreich',
					'not_helpful'      => 'Nicht hilfreich',
					'feedback_thanks'  => 'Danke für dein Feedback.',
					'error_answer'     => 'Die Chatbox kann gerade nicht antworten.',
					'no_answer'        => 'Keine Antwort erhalten.',
				),
				'admin'   => self::admin_de(),
			),
			'fr' => array(
				'name'    => 'French',
				'native'  => 'Français',
				'strings' => array(
					'welcome_message' => 'Bonjour. Comment puis je vous aider ?',
					'placeholder'     => 'Posez une question...',
					'launcher_label'  => 'Chat',
					'instructions'     => 'Répondez aux questions à partir de la base de connaissances sélectionnée du site. Soyez clair, utile et honnête. Si la réponse ne se trouve pas dans la base de connaissances, dites que vous ne savez pas d après le contenu disponible du site.',
					'send'             => 'Envoyer',
					'close'            => 'Fermer',
					'typing'           => 'Rédaction...',
					'sources'          => 'Sources',
					'source'           => 'Source',
					'helpful'          => 'Utile',
					'not_helpful'      => 'Pas utile',
					'feedback_thanks'  => 'Merci pour votre retour.',
					'error_answer'     => 'La chatbox ne peut pas répondre pour le moment.',
					'no_answer'        => 'Aucune réponse reçue.',
				),
				'admin'   => self::admin_fr(),
			),
		);
	}

	/**
	 * English admin strings.
	 */
	private static function admin_en(): array {
		return array(
			'plugin_name' => "Jeroen's Chatbox",
			'admin_title' => "Jeroen's Chatbox Manager",
			'admin_description' => "Select pages, sync them to a vector store, then publish Jeroen's Chatbox on your site.",
			'sections_label' => "Jeroen's Chatbox sections",
			'tab_knowledge' => 'Knowledge Base',
			'tab_chatbox' => 'Chatbox',
			'tab_tools' => 'Tools',
			'tab_channels' => 'Channels',
			'tab_design' => 'Design',
			'tab_analytics' => 'Analytics',
			'tab_security' => 'Security',
			'tab_api' => 'OpenAI API',
			'tab_settings' => 'Settings',
			'selected_pages' => 'Selected Pages',
			'vector_store' => 'Vector Store',
			'loading' => 'Loading',
			'sync_to_vector_store' => 'Sync to Vector Store',
			'available_content' => 'Available Content',
			'search_pages' => 'Search pages...',
			'page_metadata_editor' => 'Page Metadata Editor',
			'select_page_to_edit' => 'Select a page to edit its metadata.',
			'page' => 'Page',
			'editor_summary' => 'Editor summary',
			'tags' => 'Tags',
			'priority' => 'Priority',
			'save_metadata' => 'Save Metadata',
			'no_content_found' => 'No content found.',
			'not_connected' => 'Not connected',
			'working' => 'Working...',
			'saving' => 'Saving...',
			'settings_saved' => 'Settings saved.',
			'settings_saved_reload' => 'Settings saved. Reloading the admin panel in the selected language.',
			'metadata_saved' => 'Metadata saved.',
			'save_settings' => 'Save settings',
			'chatbox_setup' => 'Chatbox setup',
			'plugin_language' => 'Plugin and admin language',
			'plugin_language_help' => 'Controls the admin panel, the front end chatbox labels and tells the AI which language to answer in. If your texts are still set to plugin defaults, they update when you change this.',
			'language_help_simple' => 'Available languages are English, Dutch, German and French.',
			'language_explanation' => 'The selected language changes the admin panel, chatbox interface text and adds an answer language rule to the AI instructions.',
			'chatbox_name' => 'Chatbox name',
			'model' => 'Model',
			'instructions' => 'Instructions',
			'max_answer_tokens' => 'Maximum answer tokens',
			'answer_behaviour' => 'Answer behaviour',
			'answer_behaviour_p1' => "Jeroen's Chatbox uses your selected pages first. The fallback instruction tells it to be honest when the site content does not contain the answer.",
			'answer_behaviour_p2' => 'Best use cases are support, opening hours, product details, booking questions and content guidance.',
			'retrieval_tools' => 'Retrieval tools',
			'enable_file_search' => 'Enable file search',
			'enable_file_search_help' => 'Use the OpenAI vector store as the chatbox knowledge base.',
			'include_sources' => 'Include source search results in API response',
			'max_file_results' => 'Maximum file search results',
			'remember_context' => 'Remember short session context',
			'history_messages' => 'History messages per chat',
			'session_lifetime' => 'Session memory lifetime in minutes',
			'available_tools' => 'Available tools',
			'file_search' => 'File search',
			'file_search_desc' => 'Connected to selected WordPress pages.',
			'feedback' => 'Feedback',
			'feedback_desc' => 'Stores thumbs up and down events.',
			'analytics' => 'Analytics',
			'analytics_desc' => 'Stores usage metrics when logging is enabled.',
			'website_visibility' => 'Website visibility',
			'frontend_enabled' => "Enable Jeroen's Chatbox on the front end",
			'frontend_enabled_help' => 'Turn this off to hide the chatbox everywhere.',
			'auto_embed' => 'Auto embed a floating chatbox on public pages',
			'auto_embed_help' => 'Turn this on if you want the chatbox visible without placing a shortcode.',
			'start_open' => 'Open the chatbox by default',
			'show_on_mobile' => 'Show on mobile',
			'launcher_button_text' => 'Launcher button text',
			'stacking_order' => 'Stacking order',
			'stacking_order_help' => 'Raise this if another plugin or theme element covers the chatbox.',
			'where_to_show' => 'Where to show it',
			'show_home' => 'Show on the home page',
			'show_pages' => 'Show on pages',
			'show_posts' => 'Show on posts',
			'show_archives' => 'Show on archive pages',
			'exclude_page_ids' => 'Exclude page IDs',
			'exclude_page_ids_help' => 'Use commas. Example: 12, 48, 95.',
			'exclude_url_paths' => 'Exclude URL paths',
			'exclude_url_paths_help' => 'One path per line. Example: /checkout or /privacy-policy.',
			'shortcode' => 'Shortcode',
			'use_shortcode' => 'Use this shortcode',
			'copy' => 'Copy',
			'shortcode_help' => 'If auto embed is off, place this shortcode on the page where you want the chatbox.',
			'why_not_show' => 'Why it may not show',
			'why_not_show_p1' => 'Check that front end is enabled. Then either enable auto embed or place the shortcode on a page.',
			'why_not_show_p2' => 'If it is still hidden, check the page type settings, excluded IDs, excluded paths and mobile setting.',
			'who_can_see_chatbox' => 'Who can see the chatbox',
			'visibility_everyone' => 'Everyone who visits the website',
			'visibility_logged_in' => 'All logged in WordPress users',
			'visibility_admins' => 'Only administrators',
			'visibility_selected_users' => 'Only selected WordPress users',
			'who_can_see_help' => 'Use selected users or administrators only while testing. Switch to everyone when you want to publish it.',
			'selected_test_users' => 'Selected test users',
			'selected_test_users_help' => 'These users must be logged in before they can see the chatbox.',
			'no_users_found' => 'No WordPress users found.',
			'chat_design' => 'Chat design',
			'welcome_message_label' => 'Welcome message',
			'input_placeholder' => 'Input placeholder',
			'accent_color' => 'Accent color',
			'font_color' => 'Font colour',
			'background_color' => 'Background colour',
			'user_bubble_color' => 'User bubble colour',
			'user_bubble_text_color' => 'User bubble text colour',
			'assistant_bubble_color' => 'Assistant bubble colour',
			'assistant_bubble_text_color' => 'Assistant bubble text colour',
			'bubble_style' => 'Chat bubble style',
			'bubble_style_soft' => 'Soft rounded',
			'bubble_style_round' => 'Round',
			'bubble_style_square' => 'Square',
			'launcher_position' => 'Launcher position',
			'right' => 'Right',
			'left' => 'Left',
			'preview' => 'Preview',
			'preview_user_message' => 'I have a question.',
			'design_presets' => 'Preset design themes',
			'design_preset_help' => 'Choose a theme to fill the colour settings. The website only changes after you save.',
			'preview_live_note' => 'This preview updates while you edit. Your website changes only after saving.',
			'hex_value' => 'Hex value',
			'theme_purple' => 'Classic purple',
			'theme_purple_desc' => 'Bright, simple and close to the default look.',
			'theme_ocean' => 'Ocean blue',
			'theme_ocean_desc' => 'Clean blue colours for service and support sites.',
			'theme_forest' => 'Forest green',
			'theme_forest_desc' => 'Calm green colours for natural or sustainable brands.',
			'theme_midnight' => 'Midnight dark',
			'theme_midnight_desc' => 'Dark interface with clear contrast.',
			'theme_sand' => 'Warm sand',
			'theme_sand_desc' => 'Warm colours for a softer website style.',
			'security_privacy' => 'Security and privacy',
			'rate_limit_minute' => 'Rate limit per minute per IP',
			'rate_limit_hour' => 'Rate limit per hour per IP',
			'daily_token_budget' => 'Daily token budget',
			'daily_token_budget_help' => 'Set 0 to disable the daily budget cap.',
			'log_conversations' => 'Log conversations',
			'log_retention_days' => 'Log retention days',
			'redact_personal_data' => 'Redact email addresses and phone numbers before logging',
			'recommended_defaults' => 'Recommended defaults',
			'recommended_defaults_p' => 'Keep rate limiting on. Keep redaction on. Only enable debug mode while testing.',
			'api_key_saved' => 'API key saved',
			'yes' => 'Yes',
			'no' => 'No',
			'openai_api_key' => 'OpenAI API key',
			'openai_api_key_help' => 'Leave empty to keep the saved key.',
			'test_connection' => 'Test connection',
			'status' => 'Status',
			'vector_store_id' => 'Vector store id',
			'last_sync' => 'Last sync',
			'last_file_count' => 'Last file count',
			'last_file_ids' => 'Last file ids',
			'none' => 'None',
			'never' => 'Never',
			'check_sync_status' => 'Check sync status',
			'language' => 'Language',
			'advanced_settings' => 'Advanced settings',
			'debug_mode' => 'Debug mode',
			'replace_vector_store' => 'Replace old vector store on every sync',
			'delete_data_on_uninstall' => 'Delete plugin data on uninstall',
			'developer_notes' => 'Developer notes',
			'rest_namespace' => 'REST namespace',
			'plugin_version' => 'Plugin version',
			'conversations' => 'Conversations',
			'messages' => 'Messages',
			'messages_last_7_days' => 'Messages last 7 days',
			'tokens_last_7_days' => 'Tokens last 7 days',
			'avg_latency_ms' => 'Avg latency ms',
			'recent_messages' => 'Recent messages',
			'time' => 'Time',
			'role' => 'Role',
			'message' => 'Message',
			'no_messages_yet' => 'No messages yet.',
			'syncing' => 'Syncing...',
			'sync_started' => 'Knowledge base sync started. %s files sent to the vector store.',
			'checking' => 'Checking...',
			'sync_status' => 'Sync status: %s.',
			'testing' => 'Testing...',
			'connection_works' => 'Connection works.',
			'shortcode_copied' => 'Shortcode copied.',
		);
	}

	/**
	 * Dutch admin strings.
	 */
	private static function admin_nl(): array {
		return array_merge( self::admin_en(), array(
			'admin_title' => "Jeroen's Chatbox beheer",
			'admin_description' => "Selecteer pagina's, synchroniseer ze met een vector store en publiceer Jeroen's Chatbox op je site.",
			'sections_label' => "Secties van Jeroen's Chatbox",
			'tab_knowledge' => 'Kennisbank',
			'tab_tools' => 'Tools',
			'tab_channels' => 'Kanalen',
			'tab_design' => 'Ontwerp',
			'tab_analytics' => 'Statistieken',
			'tab_security' => 'Beveiliging',
			'tab_settings' => 'Instellingen',
			'selected_pages' => "Geselecteerde pagina's",
			'loading' => 'Laden',
			'sync_to_vector_store' => 'Synchroniseer naar vector store',
			'available_content' => 'Beschikbare content',
			'search_pages' => "Zoek pagina's...",
			'page_metadata_editor' => 'Metadata editor',
			'select_page_to_edit' => 'Selecteer een pagina om metadata te bewerken.',
			'page' => 'Pagina',
			'editor_summary' => 'Samenvatting voor editor',
			'tags' => 'Tags',
			'priority' => 'Prioriteit',
			'save_metadata' => 'Metadata opslaan',
			'no_content_found' => 'Geen content gevonden.',
			'not_connected' => 'Niet verbonden',
			'working' => 'Bezig...',
			'saving' => 'Opslaan...',
			'settings_saved' => 'Instellingen opgeslagen.',
			'settings_saved_reload' => 'Instellingen opgeslagen. Het beheerpaneel wordt opnieuw geladen in de gekozen taal.',
			'metadata_saved' => 'Metadata opgeslagen.',
			'save_settings' => 'Instellingen opslaan',
			'chatbox_setup' => 'Chatbox instellen',
			'plugin_language' => 'Plugin en beheertaal',
			'plugin_language_help' => 'Bepaalt de taal van het beheerpaneel, de labels van de chatbox en de taal waarin de AI antwoordt. Als je teksten nog op de standaard staan, veranderen ze mee.',
			'language_help_simple' => 'Beschikbare talen zijn Engels, Nederlands, Duits en Frans.',
			'language_explanation' => 'De gekozen taal wijzigt het beheerpaneel, de chatbox teksten en voegt een taalregel toe aan de AI instructies.',
			'chatbox_name' => 'Naam van de chatbox',
			'instructions' => 'Instructies',
			'max_answer_tokens' => 'Maximaal aantal antwoordtokens',
			'answer_behaviour' => 'Antwoordgedrag',
			'answer_behaviour_p1' => "Jeroen's Chatbox gebruikt eerst je geselecteerde pagina's. De fallback instructie zorgt dat de chatbox eerlijk is als het antwoord niet in de site content staat.",
			'answer_behaviour_p2' => 'Goede toepassingen zijn support, openingstijden, productdetails, boekingsvragen en contentadvies.',
			'retrieval_tools' => 'Ophaaltools',
			'enable_file_search' => 'File search inschakelen',
			'enable_file_search_help' => 'Gebruik de OpenAI vector store als kennisbank voor de chatbox.',
			'include_sources' => 'Bronresultaten tonen in API reactie',
			'max_file_results' => 'Maximaal aantal file search resultaten',
			'remember_context' => 'Korte sessiecontext onthouden',
			'history_messages' => 'Geschiedenisberichten per chat',
			'session_lifetime' => 'Levensduur van sessiegeheugen in minuten',
			'available_tools' => 'Beschikbare tools',
			'file_search' => 'File search',
			'file_search_desc' => "Verbonden met geselecteerde WordPress pagina's.",
			'feedback_desc' => 'Slaat duimpjes omhoog en omlaag op.',
			'analytics_desc' => 'Slaat gebruiksstatistieken op als logging aanstaat.',
			'website_visibility' => 'Zichtbaarheid op website',
			'frontend_enabled' => "Jeroen's Chatbox inschakelen op de voorkant",
			'frontend_enabled_help' => 'Zet dit uit om de chatbox overal te verbergen.',
			'auto_embed' => 'Zwevende chatbox automatisch tonen op openbare pagina’s',
			'auto_embed_help' => 'Zet dit aan als je de chatbox wilt tonen zonder shortcode.',
			'start_open' => 'Chatbox standaard openklappen',
			'show_on_mobile' => 'Tonen op mobiel',
			'launcher_button_text' => 'Tekst op de knop',
			'stacking_order' => 'Stapelhoogte',
			'stacking_order_help' => 'Verhoog dit als een thema of plugin over de chatbox heen valt.',
			'where_to_show' => 'Waar tonen',
			'show_home' => 'Tonen op de homepage',
			'show_pages' => "Tonen op pagina's",
			'show_posts' => 'Tonen op berichten',
			'show_archives' => "Tonen op archiefpagina's",
			'exclude_page_ids' => "Pagina ID's uitsluiten",
			'exclude_page_ids_help' => 'Gebruik komma’s. Voorbeeld: 12, 48, 95.',
			'exclude_url_paths' => 'URL paden uitsluiten',
			'exclude_url_paths_help' => 'Eén pad per regel. Voorbeeld: /checkout of /privacy-policy.',
			'use_shortcode' => 'Gebruik deze shortcode',
			'copy' => 'Kopiëren',
			'shortcode_help' => 'Als automatisch tonen uitstaat, plaats je deze shortcode op de pagina waar je de chatbox wilt.',
			'why_not_show' => 'Waarom hij niet zichtbaar is',
			'why_not_show_p1' => 'Controleer of de voorkant is ingeschakeld. Zet daarna automatisch tonen aan of plaats de shortcode op een pagina.',
			'why_not_show_p2' => "Als hij nog verborgen is, controleer je paginatypes, uitgesloten ID's, uitgesloten paden en mobiel.",
			'who_can_see_chatbox' => 'Wie mag de chatbox zien',
			'visibility_everyone' => 'Iedereen die de website bezoekt',
			'visibility_logged_in' => 'Alle ingelogde WordPress gebruikers',
			'visibility_admins' => 'Alleen beheerders',
			'visibility_selected_users' => 'Alleen geselecteerde WordPress gebruikers',
			'who_can_see_help' => 'Gebruik geselecteerde gebruikers of alleen beheerders tijdens het testen. Zet dit op iedereen zodra je wilt publiceren.',
			'selected_test_users' => 'Geselecteerde testgebruikers',
			'selected_test_users_help' => 'Deze gebruikers moeten ingelogd zijn voordat zij de chatbox kunnen zien.',
			'no_users_found' => 'Geen WordPress gebruikers gevonden.',
			'chat_design' => 'Chat ontwerp',
			'welcome_message_label' => 'Welkomstbericht',
			'input_placeholder' => 'Placeholder van invoerveld',
			'accent_color' => 'Accentkleur',
			'font_color' => 'Tekstkleur',
			'background_color' => 'Achtergrondkleur',
			'user_bubble_color' => 'Kleur gebruikersbubbel',
			'user_bubble_text_color' => 'Tekstkleur gebruikersbubbel',
			'assistant_bubble_color' => 'Kleur assistentbubbel',
			'assistant_bubble_text_color' => 'Tekstkleur assistentbubbel',
			'bubble_style' => 'Stijl van chatbubbels',
			'bubble_style_soft' => 'Zacht afgerond',
			'bubble_style_round' => 'Rond',
			'bubble_style_square' => 'Hoekig',
			'launcher_position' => 'Positie van knop',
			'right' => 'Rechts',
			'left' => 'Links',
			'preview' => 'Voorbeeld',
			'preview_user_message' => 'Ik heb een vraag.',
			'design_presets' => 'Vooraf ingestelde ontwerpen',
			'design_preset_help' => 'Kies een ontwerp om de kleurinstellingen te vullen. De website verandert pas nadat je opslaat.',
			'preview_live_note' => 'Dit voorbeeld verandert terwijl je bewerkt. Je website verandert pas na opslaan.',
			'hex_value' => 'Hex waarde',
			'theme_purple' => 'Klassiek paars',
			'theme_purple_desc' => 'Helder, simpel en dicht bij de standaardstijl.',
			'theme_ocean' => 'Oceaanblauw',
			'theme_ocean_desc' => 'Frisse blauwe kleuren voor service en support websites.',
			'theme_forest' => 'Bosgroen',
			'theme_forest_desc' => 'Rustige groene kleuren voor natuurlijke of duurzame merken.',
			'theme_midnight' => 'Donkere nacht',
			'theme_midnight_desc' => 'Donkere interface met duidelijk contrast.',
			'theme_sand' => 'Warm zand',
			'theme_sand_desc' => 'Warme kleuren voor een zachtere website stijl.',
			'security_privacy' => 'Beveiliging en privacy',
			'rate_limit_minute' => 'Limiet per minuut per IP',
			'rate_limit_hour' => 'Limiet per uur per IP',
			'daily_token_budget' => 'Dagelijks tokenbudget',
			'daily_token_budget_help' => 'Gebruik 0 om het dagelijkse budget uit te schakelen.',
			'log_conversations' => 'Gesprekken loggen',
			'log_retention_days' => 'Log bewaartermijn in dagen',
			'redact_personal_data' => 'E mailadressen en telefoonnummers verbergen voor logging',
			'recommended_defaults' => 'Aanbevolen standaardinstellingen',
			'recommended_defaults_p' => 'Laat rate limiting aan. Laat redactie aan. Zet debug alleen aan tijdens testen.',
			'api_key_saved' => 'API key opgeslagen',
			'yes' => 'Ja',
			'no' => 'Nee',
			'openai_api_key' => 'OpenAI API key',
			'openai_api_key_help' => 'Laat leeg om de opgeslagen key te houden.',
			'test_connection' => 'Verbinding testen',
			'status' => 'Status',
			'last_sync' => 'Laatste sync',
			'last_file_count' => 'Laatste aantal bestanden',
			'last_file_ids' => 'Laatste file ID’s',
			'none' => 'Geen',
			'never' => 'Nooit',
			'check_sync_status' => 'Sync status controleren',
			'language' => 'Taal',
			'advanced_settings' => 'Geavanceerde instellingen',
			'debug_mode' => 'Debug modus',
			'replace_vector_store' => 'Oude vector store vervangen bij elke sync',
			'delete_data_on_uninstall' => 'Plugin data verwijderen bij deinstallatie',
			'developer_notes' => 'Notities voor ontwikkelaars',
			'rest_namespace' => 'REST namespace',
			'plugin_version' => 'Plugin versie',
			'conversations' => 'Gesprekken',
			'messages' => 'Berichten',
			'messages_last_7_days' => 'Berichten laatste 7 dagen',
			'tokens_last_7_days' => 'Tokens laatste 7 dagen',
			'avg_latency_ms' => 'Gem. vertraging ms',
			'recent_messages' => 'Recente berichten',
			'time' => 'Tijd',
			'role' => 'Rol',
			'message' => 'Bericht',
			'no_messages_yet' => 'Nog geen berichten.',
			'syncing' => 'Synchroniseren...',
			'sync_started' => 'Kennisbank sync gestart. %s bestanden verzonden naar de vector store.',
			'checking' => 'Controleren...',
			'sync_status' => 'Sync status: %s.',
			'testing' => 'Testen...',
			'connection_works' => 'Verbinding werkt.',
			'shortcode_copied' => 'Shortcode gekopieerd.',
			'plugin_name' => "Jeroen's Chatbox",
			'tab_chatbox' => 'Chatbox',
			'tab_api' => 'OpenAI API',
			'vector_store' => 'Vector store',
			'vector_store_id' => 'Vector store ID',
			'model' => 'Model',
			'feedback' => 'Feedback',
			'analytics' => 'Statistieken',
			'shortcode' => 'Shortcode',
		) );
	}

	/**
	 * German admin strings.
	 */
	private static function admin_de(): array {
		return array_merge( self::admin_en(), array(
			'admin_title' => "Jeroen's Chatbox Verwaltung",
			'admin_description' => "Wähle Seiten aus, synchronisiere sie mit einem Vector Store und veröffentliche Jeroen's Chatbox auf deiner Website.",
			'tab_knowledge' => 'Wissensdatenbank',
			'tab_tools' => 'Tools',
			'tab_channels' => 'Kanäle',
			'tab_design' => 'Design',
			'tab_analytics' => 'Analysen',
			'tab_security' => 'Sicherheit',
			'tab_settings' => 'Einstellungen',
			'selected_pages' => 'Ausgewählte Seiten',
			'loading' => 'Laden',
			'sync_to_vector_store' => 'Mit Vector Store synchronisieren',
			'available_content' => 'Verfügbare Inhalte',
			'search_pages' => 'Seiten suchen...',
			'page_metadata_editor' => 'Metadaten Editor',
			'select_page_to_edit' => 'Wähle eine Seite aus, um die Metadaten zu bearbeiten.',
			'page' => 'Seite',
			'editor_summary' => 'Editor Zusammenfassung',
			'priority' => 'Priorität',
			'save_metadata' => 'Metadaten speichern',
			'no_content_found' => 'Keine Inhalte gefunden.',
			'not_connected' => 'Nicht verbunden',
			'working' => 'Wird verarbeitet...',
			'saving' => 'Speichern...',
			'settings_saved' => 'Einstellungen gespeichert.',
			'settings_saved_reload' => 'Einstellungen gespeichert. Die Verwaltung wird in der ausgewählten Sprache neu geladen.',
			'metadata_saved' => 'Metadaten gespeichert.',
			'save_settings' => 'Einstellungen speichern',
			'chatbox_setup' => 'Chatbox einrichten',
			'plugin_language' => 'Plugin und Admin Sprache',
			'plugin_language_help' => 'Steuert die Admin Oberfläche, die Chatbox Labels und die Antwortsprache der KI. Standardtexte werden beim Sprachwechsel aktualisiert.',
			'language_help_simple' => 'Verfügbare Sprachen sind Englisch, Niederländisch, Deutsch und Französisch.',
			'language_explanation' => 'Die ausgewählte Sprache ändert die Admin Oberfläche, die Chatbox Texte und die Sprachregel für die KI.',
			'chatbox_name' => 'Name der Chatbox',
			'instructions' => 'Anweisungen',
			'max_answer_tokens' => 'Maximale Antwort Tokens',
			'answer_behaviour' => 'Antwortverhalten',
			'answer_behaviour_p1' => "Jeroen's Chatbox verwendet zuerst die ausgewählten Seiten. Die Fallback Anweisung sorgt dafür, dass die Chatbox ehrlich bleibt, wenn der Inhalt keine Antwort enthält.",
			'answer_behaviour_p2' => 'Gute Anwendungsfälle sind Support, Öffnungszeiten, Produktdetails, Buchungsfragen und Content Beratung.',
			'retrieval_tools' => 'Abruf Tools',
			'enable_file_search' => 'File Search aktivieren',
			'enable_file_search_help' => 'Nutze den OpenAI Vector Store als Wissensdatenbank der Chatbox.',
			'include_sources' => 'Quellresultate in API Antwort einbeziehen',
			'max_file_results' => 'Maximale File Search Ergebnisse',
			'remember_context' => 'Kurzen Sitzungskontext merken',
			'history_messages' => 'Verlaufsnachrichten pro Chat',
			'session_lifetime' => 'Sitzungsspeicher in Minuten',
			'website_visibility' => 'Sichtbarkeit auf der Website',
			'frontend_enabled' => "Jeroen's Chatbox im Frontend aktivieren",
			'frontend_enabled_help' => 'Ausschalten, um die Chatbox überall zu verstecken.',
			'auto_embed' => 'Schwebende Chatbox automatisch auf öffentlichen Seiten einbetten',
			'auto_embed_help' => 'Aktiviere dies, wenn die Chatbox ohne Shortcode sichtbar sein soll.',
			'start_open' => 'Chatbox standardmäßig öffnen',
			'show_on_mobile' => 'Auf Mobilgeräten anzeigen',
			'launcher_button_text' => 'Text der Startschaltfläche',
			'stacking_order' => 'Stapelreihenfolge',
			'stacking_order_help' => 'Erhöhe diesen Wert, wenn ein Theme oder Plugin die Chatbox überdeckt.',
			'where_to_show' => 'Wo anzeigen',
			'show_home' => 'Auf der Startseite anzeigen',
			'show_pages' => 'Auf Seiten anzeigen',
			'show_posts' => 'Auf Beiträgen anzeigen',
			'show_archives' => 'Auf Archivseiten anzeigen',
			'exclude_page_ids' => 'Seiten IDs ausschließen',
			'exclude_url_paths' => 'URL Pfade ausschließen',
			'chat_design' => 'Chat Design',
			'welcome_message_label' => 'Begrüßung',
			'input_placeholder' => 'Platzhalter im Eingabefeld',
			'accent_color' => 'Akzentfarbe',
			'font_color' => 'Schriftfarbe',
			'background_color' => 'Hintergrundfarbe',
			'user_bubble_color' => 'Farbe der Nutzerblase',
			'user_bubble_text_color' => 'Textfarbe der Nutzerblase',
			'assistant_bubble_color' => 'Farbe der Assistentenblase',
			'assistant_bubble_text_color' => 'Textfarbe der Assistentenblase',
			'bubble_style' => 'Stil der Chatblasen',
			'bubble_style_soft' => 'Weich gerundet',
			'bubble_style_round' => 'Rund',
			'bubble_style_square' => 'Eckig',
			'launcher_position' => 'Position der Startschaltfläche',
			'right' => 'Rechts',
			'left' => 'Links',
			'preview' => 'Vorschau',
			'preview_user_message' => 'Ich habe eine Frage.',
			'design_presets' => 'Voreingestellte Designs',
			'design_preset_help' => 'Wähle ein Design, um die Farbeinstellungen zu füllen. Die Website ändert sich erst nach dem Speichern.',
			'preview_live_note' => 'Diese Vorschau aktualisiert sich beim Bearbeiten. Die Website ändert sich erst nach dem Speichern.',
			'hex_value' => 'Hex Wert',
			'theme_purple' => 'Klassisches Lila',
			'theme_purple_desc' => 'Hell, einfach und nah am Standarddesign.',
			'theme_ocean' => 'Ozeanblau',
			'theme_ocean_desc' => 'Klare blaue Farben für Service und Support Websites.',
			'theme_forest' => 'Waldgrün',
			'theme_forest_desc' => 'Ruhige grüne Farben für natürliche oder nachhaltige Marken.',
			'theme_midnight' => 'Mitternacht dunkel',
			'theme_midnight_desc' => 'Dunkle Oberfläche mit klarem Kontrast.',
			'theme_sand' => 'Warmer Sand',
			'theme_sand_desc' => 'Warme Farben für einen weicheren Website Stil.',
			'security_privacy' => 'Sicherheit und Datenschutz',
			'rate_limit_minute' => 'Limit pro Minute je IP',
			'rate_limit_hour' => 'Limit pro Stunde je IP',
			'daily_token_budget' => 'Tägliches Token Budget',
			'log_conversations' => 'Gespräche protokollieren',
			'log_retention_days' => 'Log Aufbewahrung in Tagen',
			'recommended_defaults' => 'Empfohlene Standards',
			'api_key_saved' => 'API Key gespeichert',
			'yes' => 'Ja',
			'no' => 'Nein',
			'openai_api_key' => 'OpenAI API Key',
			'test_connection' => 'Verbindung testen',
			'last_sync' => 'Letzte Synchronisierung',
			'last_file_count' => 'Letzte Dateianzahl',
			'none' => 'Keine',
			'never' => 'Nie',
			'check_sync_status' => 'Sync Status prüfen',
			'language' => 'Sprache',
			'advanced_settings' => 'Erweiterte Einstellungen',
			'debug_mode' => 'Debug Modus',
			'delete_data_on_uninstall' => 'Plugin Daten bei Deinstallation löschen',
			'developer_notes' => 'Entwicklernotizen',
			'conversations' => 'Gespräche',
			'messages' => 'Nachrichten',
			'recent_messages' => 'Neueste Nachrichten',
			'time' => 'Zeit',
			'role' => 'Rolle',
			'message' => 'Nachricht',
			'no_messages_yet' => 'Noch keine Nachrichten.',
			'syncing' => 'Synchronisieren...',
			'checking' => 'Prüfen...',
			'testing' => 'Testen...',
			'connection_works' => 'Verbindung funktioniert.',
			'shortcode_copied' => 'Shortcode kopiert.',
			'plugin_name' => "Jeroen's Chatbox",
			'sections_label' => "Jeroen's Chatbox Bereiche",
			'tab_chatbox' => 'Chatbox',
			'tab_api' => 'OpenAI API',
			'vector_store' => 'Vector Store',
			'vector_store_id' => 'Vector Store ID',
			'model' => 'Modell',
			'tags' => 'Tags',
			'available_tools' => 'Verfügbare Tools',
			'file_search' => 'File Search',
			'file_search_desc' => 'Mit ausgewählten WordPress Seiten verbunden.',
			'feedback' => 'Feedback',
			'feedback_desc' => 'Speichert Bewertungen mit Daumen hoch und runter.',
			'analytics' => 'Analysen',
			'analytics_desc' => 'Speichert Nutzungsdaten, wenn Logging aktiviert ist.',
			'exclude_page_ids_help' => 'Kommas verwenden. Beispiel: 12, 48, 95.',
			'exclude_url_paths_help' => 'Ein Pfad pro Zeile. Beispiel: /checkout oder /privacy-policy.',
			'shortcode' => 'Shortcode',
			'use_shortcode' => 'Diesen Shortcode verwenden',
			'copy' => 'Kopieren',
			'shortcode_help' => 'Wenn die automatische Einbettung aus ist, platziere diesen Shortcode auf der gewünschten Seite.',
			'why_not_show' => 'Warum sie nicht angezeigt wird',
			'why_not_show_p1' => 'Prüfe, ob das Frontend aktiviert ist. Aktiviere danach die automatische Einbettung oder platziere den Shortcode auf einer Seite.',
			'why_not_show_p2' => 'Wenn sie noch verborgen ist, prüfe Seitentypen, ausgeschlossene IDs, ausgeschlossene Pfade und Mobilgeräte.',
			'who_can_see_chatbox' => 'Wer kann die Chatbox sehen',
			'visibility_everyone' => 'Alle Besucher der Website',
			'visibility_logged_in' => 'Alle angemeldeten WordPress Benutzer',
			'visibility_admins' => 'Nur Administratoren',
			'visibility_selected_users' => 'Nur ausgewählte WordPress Benutzer',
			'who_can_see_help' => 'Nutze ausgewählte Benutzer oder Administratoren nur zum Testen. Wähle alle Besucher, wenn du veröffentlichen willst.',
			'selected_test_users' => 'Ausgewählte Testbenutzer',
			'selected_test_users_help' => 'Diese Benutzer müssen angemeldet sein, bevor sie die Chatbox sehen können.',
			'no_users_found' => 'Keine WordPress Benutzer gefunden.',
			'daily_token_budget_help' => 'Auf 0 setzen, um das tägliche Budget auszuschalten.',
			'redact_personal_data' => 'E Mail Adressen und Telefonnummern vor dem Logging entfernen',
			'recommended_defaults_p' => 'Rate Limiting eingeschaltet lassen. Redaction eingeschaltet lassen. Debug nur beim Testen aktivieren.',
			'openai_api_key_help' => 'Leer lassen, um den gespeicherten Key zu behalten.',
			'status' => 'Status',
			'last_file_ids' => 'Letzte File IDs',
			'replace_vector_store' => 'Alten Vector Store bei jeder Synchronisierung ersetzen',
			'rest_namespace' => 'REST Namespace',
			'plugin_version' => 'Plugin Version',
			'messages_last_7_days' => 'Nachrichten der letzten 7 Tage',
			'tokens_last_7_days' => 'Tokens der letzten 7 Tage',
			'avg_latency_ms' => 'Durchschnittliche Latenz ms',
			'sync_started' => 'Wissensdatenbank Synchronisierung gestartet. %s Dateien an den Vector Store gesendet.',
			'sync_status' => 'Sync Status: %s.',
		) );
	}

	/**
	 * French admin strings.
	 */
	private static function admin_fr(): array {
		return array_merge( self::admin_en(), array(
			'admin_title' => "Gestion de Jeroen's Chatbox",
			'admin_description' => "Sélectionnez des pages, synchronisez les avec un vector store, puis publiez Jeroen's Chatbox sur votre site.",
			'tab_knowledge' => 'Base de connaissances',
			'tab_tools' => 'Outils',
			'tab_channels' => 'Canaux',
			'tab_design' => 'Design',
			'tab_analytics' => 'Analyses',
			'tab_security' => 'Sécurité',
			'tab_settings' => 'Réglages',
			'selected_pages' => 'Pages sélectionnées',
			'loading' => 'Chargement',
			'sync_to_vector_store' => 'Synchroniser vers le vector store',
			'available_content' => 'Contenu disponible',
			'search_pages' => 'Rechercher des pages...',
			'page_metadata_editor' => 'Éditeur de métadonnées',
			'select_page_to_edit' => 'Sélectionnez une page pour modifier ses métadonnées.',
			'page' => 'Page',
			'editor_summary' => 'Résumé éditeur',
			'priority' => 'Priorité',
			'save_metadata' => 'Enregistrer les métadonnées',
			'no_content_found' => 'Aucun contenu trouvé.',
			'not_connected' => 'Non connecté',
			'working' => 'Traitement...',
			'saving' => 'Enregistrement...',
			'settings_saved' => 'Réglages enregistrés.',
			'settings_saved_reload' => 'Réglages enregistrés. Le panneau admin se recharge dans la langue choisie.',
			'metadata_saved' => 'Métadonnées enregistrées.',
			'save_settings' => 'Enregistrer les réglages',
			'chatbox_setup' => 'Configuration de la chatbox',
			'plugin_language' => 'Langue du plugin et de l admin',
			'plugin_language_help' => 'Contrôle le panneau admin, les libellés de la chatbox et la langue de réponse de l IA. Les textes par défaut changent avec la langue.',
			'language_help_simple' => 'Les langues disponibles sont l anglais, le néerlandais, l allemand et le français.',
			'language_explanation' => 'La langue choisie modifie le panneau admin, les textes de la chatbox et ajoute une règle de langue aux instructions de l IA.',
			'chatbox_name' => 'Nom de la chatbox',
			'instructions' => 'Instructions',
			'max_answer_tokens' => 'Tokens de réponse maximum',
			'answer_behaviour' => 'Comportement de réponse',
			'answer_behaviour_p1' => "Jeroen's Chatbox utilise d abord vos pages sélectionnées. L instruction de secours l aide à rester honnête quand le contenu du site ne contient pas la réponse.",
			'answer_behaviour_p2' => 'Bons usages: support, horaires, détails produits, questions de réservation et aide au contenu.',
			'retrieval_tools' => 'Outils de recherche',
			'enable_file_search' => 'Activer File Search',
			'enable_file_search_help' => 'Utilisez le vector store OpenAI comme base de connaissances de la chatbox.',
			'include_sources' => 'Inclure les résultats source dans la réponse API',
			'max_file_results' => 'Nombre maximal de résultats File Search',
			'remember_context' => 'Mémoriser un court contexte de session',
			'history_messages' => 'Messages d historique par chat',
			'session_lifetime' => 'Durée de la mémoire de session en minutes',
			'website_visibility' => 'Visibilité sur le site',
			'frontend_enabled' => "Activer Jeroen's Chatbox côté site",
			'frontend_enabled_help' => 'Désactivez ceci pour masquer la chatbox partout.',
			'auto_embed' => 'Afficher automatiquement une chatbox flottante sur les pages publiques',
			'auto_embed_help' => 'Activez ceci pour afficher la chatbox sans shortcode.',
			'start_open' => 'Ouvrir la chatbox par défaut',
			'show_on_mobile' => 'Afficher sur mobile',
			'launcher_button_text' => 'Texte du bouton lanceur',
			'stacking_order' => 'Ordre d empilement',
			'where_to_show' => 'Où afficher',
			'show_home' => 'Afficher sur la page d accueil',
			'show_pages' => 'Afficher sur les pages',
			'show_posts' => 'Afficher sur les articles',
			'show_archives' => 'Afficher sur les archives',
			'exclude_page_ids' => 'Exclure des ID de pages',
			'exclude_url_paths' => 'Exclure des chemins URL',
			'chat_design' => 'Design du chat',
			'welcome_message_label' => 'Message de bienvenue',
			'input_placeholder' => 'Placeholder du champ',
			'accent_color' => 'Couleur d accent',
			'font_color' => 'Couleur du texte',
			'background_color' => 'Couleur de fond',
			'user_bubble_color' => 'Couleur de la bulle utilisateur',
			'user_bubble_text_color' => 'Couleur du texte utilisateur',
			'assistant_bubble_color' => 'Couleur de la bulle assistant',
			'assistant_bubble_text_color' => 'Couleur du texte assistant',
			'bubble_style' => 'Style des bulles',
			'bubble_style_soft' => 'Arrondi doux',
			'bubble_style_round' => 'Rond',
			'bubble_style_square' => 'Carré',
			'launcher_position' => 'Position du bouton',
			'right' => 'Droite',
			'left' => 'Gauche',
			'preview' => 'Aperçu',
			'preview_user_message' => 'J ai une question.',
			'design_presets' => 'Thèmes prédéfinis',
			'design_preset_help' => 'Choisissez un thème pour remplir les réglages de couleur. Le site change seulement après enregistrement.',
			'preview_live_note' => 'Cet aperçu se met à jour pendant la modification. Le site change seulement après enregistrement.',
			'hex_value' => 'Valeur hex',
			'theme_purple' => 'Violet classique',
			'theme_purple_desc' => 'Clair, simple et proche du style par défaut.',
			'theme_ocean' => 'Bleu océan',
			'theme_ocean_desc' => 'Couleurs bleues claires pour les sites de service et support.',
			'theme_forest' => 'Vert forêt',
			'theme_forest_desc' => 'Couleurs vertes calmes pour les marques naturelles ou durables.',
			'theme_midnight' => 'Nuit sombre',
			'theme_midnight_desc' => 'Interface sombre avec contraste net.',
			'theme_sand' => 'Sable chaud',
			'theme_sand_desc' => 'Couleurs chaudes pour un style de site plus doux.',
			'security_privacy' => 'Sécurité et confidentialité',
			'rate_limit_minute' => 'Limite par minute et par IP',
			'rate_limit_hour' => 'Limite par heure et par IP',
			'daily_token_budget' => 'Budget quotidien de tokens',
			'log_conversations' => 'Journaliser les conversations',
			'log_retention_days' => 'Conservation des logs en jours',
			'recommended_defaults' => 'Réglages recommandés',
			'api_key_saved' => 'Clé API enregistrée',
			'yes' => 'Oui',
			'no' => 'Non',
			'openai_api_key' => 'Clé API OpenAI',
			'test_connection' => 'Tester la connexion',
			'last_sync' => 'Dernière synchronisation',
			'last_file_count' => 'Dernier nombre de fichiers',
			'none' => 'Aucun',
			'never' => 'Jamais',
			'check_sync_status' => 'Vérifier le statut de synchronisation',
			'language' => 'Langue',
			'advanced_settings' => 'Réglages avancés',
			'debug_mode' => 'Mode debug',
			'delete_data_on_uninstall' => 'Supprimer les données à la désinstallation',
			'developer_notes' => 'Notes développeur',
			'conversations' => 'Conversations',
			'messages' => 'Messages',
			'recent_messages' => 'Messages récents',
			'time' => 'Heure',
			'role' => 'Rôle',
			'message' => 'Message',
			'no_messages_yet' => 'Aucun message.',
			'syncing' => 'Synchronisation...',
			'checking' => 'Vérification...',
			'testing' => 'Test...',
			'connection_works' => 'La connexion fonctionne.',
			'shortcode_copied' => 'Shortcode copié.',
			'plugin_name' => "Jeroen's Chatbox",
			'sections_label' => "Sections de Jeroen's Chatbox",
			'tab_chatbox' => 'Chatbox',
			'tab_api' => 'API OpenAI',
			'vector_store' => 'Vector store',
			'vector_store_id' => 'ID du vector store',
			'model' => 'Modèle',
			'tags' => 'Tags',
			'available_tools' => 'Outils disponibles',
			'file_search' => 'File Search',
			'file_search_desc' => 'Connecté aux pages WordPress sélectionnées.',
			'feedback' => 'Feedback',
			'feedback_desc' => 'Enregistre les avis positifs et négatifs.',
			'analytics' => 'Analyses',
			'analytics_desc' => 'Enregistre les statistiques d utilisation quand les logs sont activés.',
			'exclude_page_ids_help' => 'Utilisez des virgules. Exemple: 12, 48, 95.',
			'exclude_url_paths_help' => 'Un chemin par ligne. Exemple: /checkout ou /privacy-policy.',
			'stacking_order_help' => 'Augmentez cette valeur si un thème ou plugin couvre la chatbox.',
			'shortcode' => 'Shortcode',
			'use_shortcode' => 'Utiliser ce shortcode',
			'copy' => 'Copier',
			'shortcode_help' => 'Si l intégration automatique est désactivée, placez ce shortcode sur la page souhaitée.',
			'why_not_show' => 'Pourquoi elle ne s affiche pas',
			'why_not_show_p1' => 'Vérifiez que le front end est activé. Activez ensuite l intégration automatique ou placez le shortcode sur une page.',
			'why_not_show_p2' => 'Si elle reste masquée, vérifiez les types de pages, les ID exclus, les chemins exclus et le réglage mobile.',
			'who_can_see_chatbox' => 'Qui peut voir la chatbox',
			'visibility_everyone' => 'Tous les visiteurs du site',
			'visibility_logged_in' => 'Tous les utilisateurs WordPress connectés',
			'visibility_admins' => 'Administrateurs uniquement',
			'visibility_selected_users' => 'Utilisateurs WordPress sélectionnés uniquement',
			'who_can_see_help' => 'Utilisez les utilisateurs sélectionnés ou les administrateurs pendant le test. Choisissez tous les visiteurs quand vous voulez publier.',
			'selected_test_users' => 'Utilisateurs de test sélectionnés',
			'selected_test_users_help' => 'Ces utilisateurs doivent être connectés avant de voir la chatbox.',
			'no_users_found' => 'Aucun utilisateur WordPress trouvé.',
			'daily_token_budget_help' => 'Mettez 0 pour désactiver le budget quotidien.',
			'redact_personal_data' => 'Masquer les e mails et numéros de téléphone avant logging',
			'recommended_defaults_p' => 'Gardez la limitation active. Gardez la rédaction active. Activez le debug seulement pendant les tests.',
			'openai_api_key_help' => 'Laissez vide pour garder la clé enregistrée.',
			'status' => 'Statut',
			'last_file_ids' => 'Derniers ID de fichiers',
			'replace_vector_store' => 'Remplacer l ancien vector store à chaque synchronisation',
			'rest_namespace' => 'Namespace REST',
			'plugin_version' => 'Version du plugin',
			'messages_last_7_days' => 'Messages des 7 derniers jours',
			'tokens_last_7_days' => 'Tokens des 7 derniers jours',
			'avg_latency_ms' => 'Latence moyenne ms',
			'sync_started' => 'Synchronisation de la base de connaissances lancée. %s fichiers envoyés au vector store.',
			'sync_status' => 'Statut de synchronisation: %s.',
		) );
	}

	/**
	 * Supported language codes.
	 */
	public static function codes(): array {
		return array_keys( self::languages() );
	}

	/**
	 * Normalize language code.
	 *
	 * @param string $language Language code.
	 */
	public static function normalize( string $language ): string {
		$language = strtolower( sanitize_key( $language ) );
		return in_array( $language, self::codes(), true ) ? $language : 'en';
	}

	/**
	 * Return language options for the admin app.
	 */
	public static function admin_options(): array {
		$options = array();
		foreach ( self::languages() as $code => $language ) {
			$options[] = array(
				'code'   => $code,
				'name'   => $language['name'],
				'native' => $language['native'],
			);
		}
		return $options;
	}

	/**
	 * Get a front-end language string.
	 *
	 * @param string $key String key.
	 * @param string $language Language code.
	 */
	public static function text( string $key, string $language = 'en' ): string {
		$language  = self::normalize( $language );
		$languages = self::languages();
		$strings   = $languages[ $language ]['strings'] ?? array();
		$fallback  = $languages['en']['strings'] ?? array();
		return (string) ( $strings[ $key ] ?? $fallback[ $key ] ?? '' );
	}

	/**
	 * Get an admin language string.
	 *
	 * @param string $key String key.
	 * @param string $language Language code.
	 */
	public static function admin_text( string $key, string $language = 'en' ): string {
		$language  = self::normalize( $language );
		$languages = self::languages();
		$strings   = $languages[ $language ]['admin'] ?? array();
		$fallback  = $languages['en']['admin'] ?? array();
		return (string) ( $strings[ $key ] ?? $fallback[ $key ] ?? $key );
	}

	/**
	 * Get all admin JavaScript strings.
	 *
	 * @param string $language Language code.
	 */
	public static function admin_strings( string $language = 'en' ): array {
		$language  = self::normalize( $language );
		$languages = self::languages();
		return array_merge( $languages['en']['admin'] ?? array(), $languages[ $language ]['admin'] ?? array() );
	}

	/**
	 * Get all front-end JavaScript strings.
	 *
	 * @param string $language Language code.
	 */
	public static function front_end_strings( string $language = 'en' ): array {
		$language = self::normalize( $language );
		return array(
			'send'           => self::text( 'send', $language ),
			'close'          => self::text( 'close', $language ),
			'typing'         => self::text( 'typing', $language ),
			'sources'        => self::text( 'sources', $language ),
			'source'         => self::text( 'source', $language ),
			'helpful'        => self::text( 'helpful', $language ),
			'notHelpful'     => self::text( 'not_helpful', $language ),
			'feedbackThanks' => self::text( 'feedback_thanks', $language ),
			'errorAnswer'    => self::text( 'error_answer', $language ),
			'noAnswer'       => self::text( 'no_answer', $language ),
		);
	}

	/**
	 * Return all default text values for a setting key.
	 *
	 * @param string $key String key.
	 */
	public static function default_candidates( string $key ): array {
		$values = array();
		foreach ( self::codes() as $code ) {
			$value = self::text( $key, $code );
			if ( '' !== $value ) {
				$values[] = $value;
			}
		}
		return array_values( array_unique( $values ) );
	}

	/**
	 * Return answer language instruction.
	 *
	 * @param string $language Language code.
	 */
	public static function response_rule( string $language = 'en' ): string {
		$language = self::normalize( $language );
		switch ( $language ) {
			case 'nl':
				return 'Answer visitors in Dutch unless they clearly ask for another language.';
			case 'de':
				return 'Answer visitors in German unless they clearly ask for another language.';
			case 'fr':
				return 'Answer visitors in French unless they clearly ask for another language.';
			case 'en':
			default:
				return 'Answer visitors in English unless they clearly ask for another language.';
		}
	}
}
