<?php
/**
 * OpenAI API wrapper.
 *
 * @package JeroensChatbox
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class JCB_OpenAI_Client {

	/** API base URL. */
	private const BASE = 'https://api.openai.com/v1';

	/**
	 * Send JSON request.
	 *
	 * @param string     $method HTTP method.
	 * @param string     $path API path.
	 * @param array|null $body JSON body.
	 * @param int        $timeout Timeout.
	 */
	public function request( string $method, string $path, ?array $body = null, int $timeout = 45 ) {
		$key = JCB_Options::api_key();
		if ( '' === $key ) {
			return new WP_Error( 'jcb_missing_api_key', __( 'OpenAI API key is missing.', 'jeroens-chatbox' ) );
		}

		$args = array(
			'method'  => strtoupper( $method ),
			'timeout' => $timeout,
			'headers' => array(
				'Authorization' => 'Bearer ' . $key,
				'Content-Type'  => 'application/json',
			),
		);

		if ( null !== $body ) {
			$args['body'] = wp_json_encode( $body );
		}

		$response = wp_remote_request( self::BASE . $path, $args );
		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		$raw  = wp_remote_retrieve_body( $response );
		$data = json_decode( $raw, true );

		if ( $code < 200 || $code >= 300 ) {
			$message = is_array( $data ) && isset( $data['error']['message'] ) ? $data['error']['message'] : wp_remote_retrieve_response_message( $response );
			return new WP_Error( 'jcb_openai_error', $message, array( 'status' => $code, 'response' => $data ) );
		}

		return is_array( $data ) ? $data : array();
	}

	/**
	 * Create model response.
	 *
	 * @param array $payload Payload.
	 */
	public function create_response( array $payload ) {
		return $this->request( 'POST', '/responses', $payload, 90 );
	}

	/**
	 * Create vector store.
	 *
	 * @param string $name Name.
	 */
	public function create_vector_store( string $name ) {
		return $this->request(
			'POST',
			'/vector_stores',
			array(
				'name'        => $name,
				'description' => "WordPress knowledge base generated by Jeroen's Chatbox.",
				'metadata'    => array(
					'site_url' => home_url(),
					'source'   => 'wordpress',
				),
			)
		);
	}

	/**
	 * Delete vector store.
	 *
	 * @param string $vector_store_id Vector store id.
	 */
	public function delete_vector_store( string $vector_store_id ) {
		if ( '' === $vector_store_id ) {
			return array( 'deleted' => false );
		}
		return $this->request( 'DELETE', '/vector_stores/' . rawurlencode( $vector_store_id ), null, 30 );
	}

	/**
	 * Create vector store file batch.
	 *
	 * @param string $vector_store_id Vector store id.
	 * @param array  $file_ids File ids.
	 */
	public function create_file_batch( string $vector_store_id, array $file_ids ) {
		return $this->request(
			'POST',
			'/vector_stores/' . rawurlencode( $vector_store_id ) . '/file_batches',
			array( 'file_ids' => array_values( $file_ids ) ),
			60
		);
	}

	/**
	 * Retrieve a vector store file batch.
	 *
	 * @param string $vector_store_id Vector store id.
	 * @param string $batch_id Batch id.
	 */
	public function retrieve_file_batch( string $vector_store_id, string $batch_id ) {
		return $this->request( 'GET', '/vector_stores/' . rawurlencode( $vector_store_id ) . '/file_batches/' . rawurlencode( $batch_id ), null, 30 );
	}

	/**
	 * Upload file using cURL multipart form data.
	 *
	 * @param string $path File path.
	 * @param string $purpose OpenAI purpose.
	 */
	public function upload_file( string $path, string $purpose = 'assistants' ) {
		$key = JCB_Options::api_key();
		if ( '' === $key ) {
			return new WP_Error( 'jcb_missing_api_key', __( 'OpenAI API key is missing.', 'jeroens-chatbox' ) );
		}
		if ( ! file_exists( $path ) || ! is_readable( $path ) ) {
			return new WP_Error( 'jcb_file_missing', __( 'Knowledge base export file is missing.', 'jeroens-chatbox' ) );
		}
		if ( ! function_exists( 'curl_init' ) || ! class_exists( 'CURLFile' ) ) {
			return new WP_Error( 'jcb_curl_missing', __( 'The PHP cURL extension is required for file upload.', 'jeroens-chatbox' ) );
		}

		$ch = curl_init();
		curl_setopt_array(
			$ch,
			array(
				CURLOPT_URL            => self::BASE . '/files',
				CURLOPT_POST           => true,
				CURLOPT_RETURNTRANSFER => true,
				CURLOPT_TIMEOUT        => 120,
				CURLOPT_HTTPHEADER     => array( 'Authorization: Bearer ' . $key ),
				CURLOPT_POSTFIELDS     => array(
					'purpose' => $purpose,
					'file'    => new CURLFile( $path, 'text/plain', basename( $path ) ),
				),
			)
		);

		$raw      = curl_exec( $ch );
		$curl_err = curl_error( $ch );
		$code     = (int) curl_getinfo( $ch, CURLINFO_HTTP_CODE );
		curl_close( $ch );

		if ( false === $raw ) {
			return new WP_Error( 'jcb_curl_error', $curl_err );
		}
		$data = json_decode( (string) $raw, true );
		if ( $code < 200 || $code >= 300 ) {
			$message = is_array( $data ) && isset( $data['error']['message'] ) ? $data['error']['message'] : __( 'OpenAI file upload failed.', 'jeroens-chatbox' );
			return new WP_Error( 'jcb_openai_upload_error', $message, array( 'status' => $code, 'response' => $data ) );
		}
		return is_array( $data ) ? $data : array();
	}

	/**
	 * Extract readable text from a response object.
	 *
	 * @param array $response Response data.
	 */
	public static function output_text( array $response ): string {
		$text = '';
		if ( isset( $response['output_text'] ) && is_string( $response['output_text'] ) ) {
			$text = $response['output_text'];
		} elseif ( isset( $response['output'] ) && is_array( $response['output'] ) ) {
			foreach ( $response['output'] as $item ) {
				if ( isset( $item['content'] ) && is_array( $item['content'] ) ) {
					foreach ( $item['content'] as $content ) {
						if ( isset( $content['text'] ) && is_string( $content['text'] ) ) {
							$text .= $content['text'] . "\n";
						}
					}
				}
			}
		}
		return self::strip_citations( trim( $text ) );
	}

	/**
	 * Remove OpenAI file_search citation markers from answer text.
	 *
	 * The Responses API embeds inline citation markers such as 【9:8†filename】
	 * in the output text. They are meaningless to visitors, so strip them and
	 * tidy up any leftover whitespace.
	 *
	 * @param string $text Raw answer text.
	 */
	private static function strip_citations( string $text ): string {
		// Well-formed markers, e.g. 【9:8†jcb-2392-some-page】.
		$text = (string) preg_replace( '/【[^【】]*】/u', '', $text );
		// Stray or truncated marker at the end of the text.
		$text = (string) preg_replace( '/【[^【】]*$/u', '', $text );
		// Collapse leftover spaces and tidy spacing before line breaks.
		$text = (string) preg_replace( '/[ \t]{2,}/', ' ', $text );
		$text = (string) preg_replace( '/[ \t]+\n/', "\n", $text );
		$text = (string) preg_replace( '/[ \t]+([.,!?;:])/u', '$1', $text );
		return trim( $text );
	}

	/**
	 * Extract source hints from file search results when included by the API.
	 *
	 * @param array $response Response data.
	 */
	public static function file_sources( array $response ): array {
		$sources = array();
		if ( empty( $response['output'] ) || ! is_array( $response['output'] ) ) {
			return $sources;
		}

		foreach ( $response['output'] as $item ) {
			if ( empty( $item['results'] ) || ! is_array( $item['results'] ) ) {
				continue;
			}
			foreach ( $item['results'] as $result ) {
				$text = '';
				if ( isset( $result['text'] ) && is_string( $result['text'] ) ) {
					$text = $result['text'];
				} elseif ( isset( $result['content'][0]['text'] ) && is_string( $result['content'][0]['text'] ) ) {
					$text = $result['content'][0]['text'];
				}

				$title = '';
				$url   = '';
				if ( preg_match( '/Title:\s*(.+)/', $text, $match ) ) {
					$title = trim( (string) $match[1] );
				}
				if ( preg_match( '/URL:\s*(https?:\/\/\S+)/', $text, $match ) ) {
					$url = esc_url_raw( (string) $match[1] );
				}
				if ( '' === $title && isset( $result['filename'] ) ) {
					$title = (string) $result['filename'];
				}

				$key = $url ? $url : $title;
				if ( '' !== $key && ! isset( $sources[ $key ] ) ) {
					$sources[ $key ] = array(
						'title' => JCB_Sanitizer::text( $title ? $title : __( 'Source', 'jeroens-chatbox' ), 120 ),
						'url'   => $url,
					);
				}
			}
		}

		return array_values( array_slice( $sources, 0, 5 ) );
	}
}
